// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "ocppoc-cluster"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "ocppoc-cluster.example.com"

// Base domain from which the cluster domain is a subdomain.
base_domain = "example.com"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".
vsphere_server = "vcocppoc-vc.example.local"

// User on the vSphere server.
vsphere_user = "Administrator@vsphere.local"

// Password of the user on the vSphere server.
vsphere_password = "XXXXXXXXXX"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "ocppoc-cluster"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "datacenter-par01"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "management-share"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
// vm_template = "rhcos-latest"
vm_template = "RHCOS"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
machine_cidr = "10.126.72.192/27"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 3

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://dl.ocppoc-cluster.example.com:8008/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.ocppoc-cluster.example.com:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJYlRoOGZ3VTdxMXN3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURFeE1ERXdNamMxTlZvWApEVE13TURFd056RXdNamMxTlZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5T3RhSW5IQmdKemUKSFZRZk9JbkltT2JjNHZzZGtXNHNXT2tJRTEzN2MyVk9VK0E4ZjEzUWlUaGgxRzdUVDZGaDF4Q3RXdFdIei9NeAp0VzN0R2s0TW5aQ3VuS1VUcGJrWUpoK3g2VEhJRnZMNm1HSzZ0VWttbjFsd3ZaMUxJNXhZOEJ6TjJlb2wyL0hyCnhCOW40NGNIWGdUYW94ZGFRWDc1S2hZVGMwamgwWlF5Y2dMU0VGQVI2TGFUQU1UaFQ2SEtLaHlIZzlONDlDYmIKZmJwcU9OUWk0MjUzYUJabTUvYzNHM3BaZVdnVk85K2N0aVRuQk5YUU5MWm82YmNTejhrTjIyOFpydmRmckRNRAowc3owbEF0Qm5CR01Vb3ZKVmFSWktVd1RQeW1IamtCd1ZPMmhEZ0Y3L3J4T1pzQ1FmYm9kSW5OcTVFbk1hYzBzCmI2WEtDajZ3dFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVTNZc0ltZGFlZzNMT25Ua0czRi9HQmhCcVFUZ3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUVOWE9pWmhudk5XSWkrK1RJbndYaTNidUVkNCtWZnRnRXdkSDRQenN1UXIxRDVPem5WMy8ycFRINWU3CjBhRnpMd2FiWlBOYzlGbHcxRzg1eEVaQ3JncFliZmF6QWJLeG1OUEQ2UFhSblRHeEFSYXlOZTBDTGZJSkloa0EKeklySHdNbFI0NStHOGk3bVpoTnVvSmZKWm13UmVHZ0Y3QlFQckkweGx0cVU2K2ZXeGpYWUxNUTNKWXdWQmd0VQplZi9JZE41ZktQbnlIYlB0Sm9EU3d3Q2wvaXh1SCthS215SXowR1I1ZW1SY2YvZ01uaVhpWnlZY2lLbUJFcUQzCjdNTlJjdGlGZnQ1M0dPMmNmZVpoemVpSUJWYndkcDl6ek55NjRjOEw0Z3VrYmREWTZvZmlzQXN4TmlEOUNzVFkKaC9OTkZtT0czRHFQVkV2dUdkQkVnTGxhKzJjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
END_OF_WORKER_IGNITION


// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
// ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
// ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
bootstrap_ip = "10.126.72.208"
bootstrap_mac = "00:50:56:a5:c4:d7"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
//control_plane_ips = ["10.0.0.20", "10.0.0.21", "10.0.0.22"]
control_plane_ips = [ "10.126.72.210", "10.126.72.211", "10.126.72.212" ]
control_plane_macs = [ "00:50:56:a5:21:42", "00:50:56:a5:2c:51", "00:50:56:a5:66:65" ]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
compute_ips = [ "10.126.72.216", "10.126.72.217", "10.126.72.218" ]
compute_macs = [ "00:50:56:a5:21:45", "00:50:56:a5:2c:55", "00:50:56:a5:66:70" ]

vm_network = "vcocppoc-ocppoc-cluster-dpg-mgmt"
